networks:
  
  - id: 'terraclassic'
    chainId: 'columbus-5'
    hrp: 'terra'
    signer: 1ec75f8200aa0318152405d0e7729eb24e4b9b45e0a91df932c0d57756d9ebbc
    endpoint:
       rpc: 'https://rpc.terra-classic.hexxagon.io'
       rest: 'https://lcd.terra-classic.hexxagon.io'
       grpc: 'https://grpc.terra-classic.hexxagon.io'
    gas:
      price: '28.325'
      denom: 'uluna'
    domain: 1325   # terra-classic -> ascii / decimal -> sum


# Networks that already have hyperlane deployments
# but might require new warp route connections
evm_networks:
 
  # - name: 'bsc_local'
  #   signer: 95badbee842392bde45a3f4e0e83e83f5f2e8133824268d220cf58097a507bf6 
  #   chain_id: 56
  #   rpc_endpoint: 'http://localhost:8545'
  #   network: 'bscTestnet'
  #   nativeCurrency:
  #     name: 'Binance Coin'
  #     symbol: 'BNB'
  #     decimals: 18
  #   gas_price: 1000000000  # = 1 gwei

deploy:
  ism:
   

    # # hpl_ism_routing
    type: "routing"
    owner: terra1lmwng9g3gws5c9v0awxdankjl6a2psfhm8pc8z
    isms:
      56:
          type: multisig
          owner: terra1lmwng9g3gws5c9v0awxdankjl6a2psfhm8pc8z
          validators:
            56:
              addrs:
                - '570af9b7b36568c8877eebba6c6727aa9dab7268'
                - '5450447aee7b544c462c9352bef7cad049b0c2dc'
                - '0d4c1394a255568ec0ecd11795b28d1bda183ca4'
                - '24c1506142b2c859aee36474e59ace09784f71e8'
                - 'c67789546a7a983bf06453425231ab71c119153f'
                - '2d74f6edfd08261c927ddb6cb37af57ab89f0eff'
               
              threshold: 2
      1:
          type: multisig
          owner: terra1lmwng9g3gws5c9v0awxdankjl6a2psfhm8pc8z
          validators:
            1:
              addrs:
                - '03c842db86a6a3e524d4a6615390c1ea8e2b9541'
                - '94438a7de38d4548ae54df5c6010c4ebc5239eae'
                - '5450447aee7b544c462c9352bef7cad049b0c2dc'
                - 'b3ac35d3988bca8c2ffd195b1c6bee18536b317b'
                - 'b683b742b378632a5f73a2a5a45801b3489bba44'
                - '3786083ca59dc806d894104e65a13a70c2b39276'
                - '4f977a59fdc2d9e39f6d780a84d5b4add1495a36'
                - '29d783efb698f9a2d3045ef4314af1f5674f52c5'
                - '36a669703ad0e11a0382b098574903d2084be22c'
               
              threshold: 6
      1399811149:
          type: multisig
          owner: terra1lmwng9g3gws5c9v0awxdankjl6a2psfhm8pc8z
          validators:
            1399811149:
              addrs:
                - '28464752829b3ea59a497fca0bdff575c534c3ff'
                - '2b7514a2f77bd86bbf093fe6bb67d8611f51c659'
                - 'cb6bcbd0de155072a7ff486d9d7286b0f71dcc2d'
                - '4f977a59fdc2d9e39f6d780a84d5b4add1495a36'
                - '5450447aee7b544c462c9352bef7cad049b0c2dc'
               
               
              threshold: 3
      
    
  hooks:
    default:
      type: aggregate
      owner: terra1lmwng9g3gws5c9v0awxdankjl6a2psfhm8pc8z 
      hooks:
        - type: merkle

        - type: igp
          owner: terra1lmwng9g3gws5c9v0awxdankjl6a2psfhm8pc8z 
          configs:
            56:
              exchange_rate: 1805936462255558    
              gas_price: 50_000_000   # 0.05 Gwei                          
            1:
              exchange_rate: 1805936462255558   
              gas_price: 50_000_000   # 0.05 Gwei  
            1399811149:
              exchange_rate: 57675000000000000     
              gas_price: 1   # 0.05 Gwei  

          default_gas_usage: 100000
         

    required:
      type: aggregate
      owner: terra1lmwng9g3gws5c9v0awxdankjl6a2psfhm8pc8z 
      hooks:
        
        - type: pausable
          owner: terra1lmwng9g3gws5c9v0awxdankjl6a2psfhm8pc8z 
          paused: false

        - type: fee
          owner: terra1lmwng9g3gws5c9v0awxdankjl6a2psfhm8pc8z 
          fee:
            # if you didn't set the denom, it will be set as gas denom of network config
            denom: uluna
            amount: 283215
            

    #   # custom_hooks: # optional
    #   #   5:
    #   #     recipient: osmo1g3q542hpttdrj9aaczsq0tkl0uyfk7nkydklz6
    #   #     hook: osmo1g3q542hpttdrj9aaczsq0tkl0uyfk7nkydklz6
    #   # fallback_hook: osmo1g3q542hpttdrj9aaczsq0tkl0uyfk7nkydklz6 # optional
